CREATE TABLE "GCG_5838_EXPORT" (
 "ENABLED" BIT DEFAULT '0' NOT NULL,
 "COLUMNS" LONGVARCHAR,
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0 );

ALTER TABLE "GCG_5838_EXPORT" ADD CONSTRAINT "PK_ID" PRIMARY KEY  ( "ID" ) USING 0;

